### PR TITLE
Update 2

### PR DESCRIPTION
**Pull request by raymour123**
I am going to continue to work on this project and get it complete this weekend. I appreciate all the help so far and fixing my Github problem.

### CODE REVIEW

**Comment by charlesdrews** [comment]
#### Performance Evaluation

| Requirements | Incomplete (0) | Does Not Meet Expectations (1) | Meets Expectations (2) | Exceeds Expectations (3) |
|---|---|---|---|---|
| View a collection of to-do lists | | | X | n/a |
| View items on a to-do list | | X | | n/a |
| Allow the user to create a new to-do list | | X | | n/a |
| Add items to each to-do list | X | | | n/a |
| Remove items from a to-do list | X | | | n/a |
| Remove an entire to-do list | X | | | n/a |
| Use custom Java objects to contain your data | | | X | n/a |
| Display correctly in both landscape and portrait orientations  | | | X | n/a |
| Show an error message if invalid input is given  | X | | | n/a |
| **Bonus**: Persist data when the app closes and is re-opened | n/a | n/a | n/a | - |
| **Bonus**: Allow the user to check off and remove completed items | n/a | n/a | n/a | - |
| **Bonus**: Allow the user to edit previously added items | n/a | n/a | n/a | - |


Notes:

You are on the right track with this project! I think the missing features are nearly within your reach, and with a bit more time, you'll be able to implement all of them.

When it comes to adding new to-do lists, you almost have that working. The idea is to set up your adapter using the list of CustomObject1 objects held in the singleton, rather than a new array that you created as a local variable in onCreate(). Then, when you add the new to-do-list to the singleton in line 59, it will be in the data the adapter is using. The only remaining step is to call the notifyDataSetChanged() method on the adapter. (be careful to prefix your color string values with "#" though!)

In your SecondaryActivity you are just showing the same hardcoded list of items, no matter what list was clicked by the user. But you have nearly all the code you need to show the items for the selected list! You are correctly passing the "position" value of the list that was clicked through the intent, then on line 30 of SecondaryActivity you are getting the specific to-do-list object you want to display. The only thing you're missing is to use the to-do-items from that to-do-list as the input to your adapter's constructor on line 42, rather than the hard-coded array list.

Because your project, in its current condition, doesn't really meet the minimum standards for this assignment, we will need you to continue working on it so that we know you can utilize these techniques successfully. Do you think you could implement, if not all, at least a few more of the missing features by Monday? If that doesn't seem realistic, let's discuss and determine a suitable timeline.

Keep up the hard work!

---

## Score:
Based on the requirements, you can earn a maximum of  **18**  points on this project.

#### Your total score is: **8**

**Comment by raymour123** [comment]
Hey Charlie, yes I plan on finishing this project in its entirety. I'm actually almost done. I'll definitely have it completed by Monday I'm shooting to get it done tonight.

Get Outlook for Android<https://aka.ms/ghei36>



On Thu, Jul 14, 2016 at 10:34 AM -0400, "Charles Drews" <notifications@github.com<mailto:notifications@github.com>> wrote:

Performance Evaluation
Requirements    Incomplete (0)  Does Not Meet Expectations (1)  Meets Expectations (2)  Exceeds Expectations (3)
View a collection of to-do lists                        X       n/a
View items on a to-do list              X               n/a
Allow the user to create a new to-do list               X               n/a
Add items to each to-do list    X                       n/a
Remove items from a to-do list  X                       n/a
Remove an entire to-do list     X                       n/a
Use custom Java objects to contain your data                    X       n/a
Display correctly in both landscape and portrait orientations                   X       n/a
Show an error message if invalid input is given X                       n/a
Bonus: Persist data when the app closes and is re-opened        n/a     n/a     n/a     -
Bonus: Allow the user to check off and remove completed items   n/a     n/a     n/a     -
Bonus: Allow the user to edit previously added items    n/a     n/a     n/a     -

Notes:

You are on the right track with this project! I think the missing features are nearly within your reach, and with a bit more time, you'll be able to implement all of them.

When it comes to adding new to-do lists, you almost have that working. The idea is to set up your adapter using the list of CustomObject1 objects held in the singleton, rather than a new array that you created as a local variable in onCreate(). Then, when you add the new to-do-list to the singleton in line 59, it will be in the data the adapter is using. The only remaining step is to call the notifyDataSetChanged() method on the adapter. (be careful to prefix your color string values with "#" though!)

In your SecondaryActivity you are just showing the same hardcoded list of items, no matter what list was clicked by the user. But you have nearly all the code you need to show the items for the selected list! You are correctly passing the "position" value of the list that was clicked through the intent, then on line 30 of SecondaryActivity you are getting the specific to-do-list object you want to display. The only thing you're missing is to use the to-do-items from that to-do-list as the input to your adapter's constructor on line 42, rather than the hard-coded array list.

Because your project, in its current condition, doesn't really meet the minimum standards for this assignment, we will need you to continue working on it so that we know you can utilize these techniques successfully. Do you think you could implement, if not all, at least a few more of the missing features by Monday? If that doesn't seem realistic, let's discuss and determine a suitable timeline.

Keep up the hard work!

________________________________
Score:

Based on the requirements, you can earn a maximum of 18 points on this project.

Your total score is: 8

-

**Comment by charlesdrews** [comment]
What is the status of your project? I don't see a new pull request since the initial one was closed and we discussed that you would need to implement more features.

**Comment by raymour123** [comment]
Charlie,


I was just reviewing my code for my project 1 and realized that I did not really understand what I was doing then and my code is a complete mess. I have learned so much since then and can't get it functional without re-writing a bunch of the structure.


I don't know how that relates to the points/completion system but I'm going to get that done anyways. I'll perform a new pull request upon completion.


Thanks,


Raymour


________________________________

**Comment by charlesdrews** [comment]
Please do submit a new pull request. We'll grade it and give you feedback. One of the requirements for completing the course and getting post-course outcomes support is successfully completing all 4 projects, so it's important that you get this done. Can you do this over the weekend?

**Comment by raymour123** [comment]
Yes, definitely.

Get Outlook for Android<https://aka.ms/ghei36>



On Fri, Aug 12, 2016 at 9:23 AM -0400, "Charles Drews" <notifications@github.com<mailto:notifications@github.com>> wrote:


Please do submit a new pull request. We'll grade it and give you feedback. One of the requirements for completing the course and getting post-course outcomes support is successfully completing all 4 projects, so it's important that you get this done. Can you do this over the weekend?

-

**Pull request closed without merging**
